# fly.toml app configuration file generated for fa-semantic-search on 2023-08-19T22:45:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fa-semantic-search"
primary_region = "iad"
console_command = "/code/manage.py shell"

[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
